### ISSUE TITLE
SpeechState.Recording Not able to use Preview on Speechly Website Not working

### ISSUE THREAD

**Issue by Dontiwari** [speechly/speechly#193]
### Expected behaviour
Preview on website of deployed Application not working +
SpeechState.Recording is undefined ...Not able to use the recording property

### Environment

- Platform: [e.g. Mobile, Desktop, React Native]
- Package version [e.g. 1.2.3]

### Additional context
Add ny other context about the problem here.
Hi Team ... I have deployed the App on Speechly Website ...but i couldnt Review ...though i have given the site permission to use microphone.I m using Chromium.

i trid to run the below code wherein i m not getting any thing in SpeechState.Recording....While compiling it shows SpeechState.recording is undefined....
********************************************************************************************
import React, { useEffect, useRef } from 'react';
import { Grid } from '@material-ui/core';
import Details from './components/Details/Details';
import useStyles from './styles';
import { SpeechState } from "@speechly/react-client";

import { PushToTalkButton, PushToTalkButtonContainer,ErrorPanel } from '@speechly/react-ui';
import Main from './components/Main/Main';
import { useSpeechContext } from "@speechly/react-client";

import {Chart, ArcElement} from 'chart.js';

const App = () => {
const classes = useStyles();
const { speechState } = useSpeechContext();

const main = useRef(null)

const executeScroll = () => main.current.scrollIntoView()

  useEffect(() => {
    if (speechState === SpeechState.recording())
    {
      executeScroll();
    }
  }, [speechState]);

**Comment by thisismatu** [comment]
Hi @Dontiwari 👋  So it seems like your trying to execute a voice activated scroll, am i reading this right?

Our "command and control" template creates a configuration for a FAQ site that you are then able to control using voice with commands like "what's your opening hours" etc. The react template deals with the scroll logic. Maybe this would help you?

https://github.com/speechly/speechly/blob/main/templates/command-control/

**Comment by arzga** [comment]
Hi @Dontiwari,

Please use `listening` (boolean) or `clientState === ClientState.Recording` property instead of deprecated `speechState`.

I'm afraid there was stale information on react-client readme's example which has now been updated.

https://github.com/speechly/speechly/tree/main/libraries/react-client
