### ISSUE TITLE
No active SLU stream available

### ISSUE THREAD

**Issue by being-eyram** [speechly/speechly#202]
### Describe the bug
I get a NoActiveStreamException when I launch my application and tap on record button immediately and release it. 
However, when I wait for a while and tap on the button and release it does not throw any exception. 

### Expected behaviour
When I press the button, it calls the Client().startContext() method and it starts recording audio.
Upon release, it calls the Client().stopContext() method and stops audio recording. 

### Environment

- Platform: [Mobile]
- OS: [Android]
- Version [8.1 Oreo]
- Package version [0.2.0]

**Comment by thisismatu** [comment]
Hello @being-eyram 👋  Just letting you know that we are looking into the issue. Thanks for letting us know 👍

**Comment by langma** [comment]
This problem should now be fixed in release https://github.com/speechly/android-client/releases/tag/0.2.1.

**Comment by being-eyram** [comment]
Thank you for looking into it.
I'll check it out.

**Comment by being-eyram** [comment]
One more thing, I'd like to ask some questions concerning some of the API design choices.
How do I go about that?

**Comment by langma** [comment]
> One more thing, I'd like to ask some questions concerning some of the API design choices.
> How do I go about that?

You are most welcome to start a discussion at https://github.com/speechly/speechly/discussions. We are also open to suggestions and welcome PRs :)

**Comment by being-eyram** [comment]
Ssweet!!😁
