### ISSUE TITLE
Option to turn microphone off when not processing audio

### ISSUE THREAD

**Issue by JamesBrill** [speechly/speechly#226]
### What

An option to turn the microphone off when audio processing is stopped.

### Why

Native browser Speech Recognition implementations usually turn off the microphone when their `stop()` methods are called. This is reflected in the browser tab as the red recording icon disappears.

<img width="125" alt="Screenshot 2022-10-09 at 10 50 01" src="https://user-images.githubusercontent.com/2140027/194750025-f00ededd-aaa2-439c-a8e0-0026dea10af4.png">

In the Speechly Browser Client, the microphone appears to remain on permanently, even when no audio data is being streamed to the Speechly API. While it functions as expected, the visual presence of the browser recording icon can be misleading for users as was highlighted in [this issue](https://github.com/speechly/speech-recognition-polyfill/issues/30) on the Speechly Speech Recognition polyfill. Users have signalled their intent to stop collecting audio data from their microphone (e.g. by releasing a hold-to-talk button) but the website appears to still be listening to them. This could raise privacy or trust issues in the website.

### How

It looks like the Browser Client already has a [means](https://github.com/speechly/speechly/blob/main/libraries/browser-client/src/microphone/browser_microphone.ts#L100) of "closing" the microphone. It seems this is not used on `BrowserClient.stop`, perhaps to make restarting audio processing more efficient.

If this is not the default behaviour on `stop()`, perhaps an option could be passed into that method to additionally close the microphone. e.g.

```
client.stop(stopDelayMs, { closeMicrophone: true })
```

Alternatively, this option could be provided when instantiating the Browser Client, initialising it, or when attaching a microphone to it.

A further alternative is to make this the default behaviour if restarting the microphone turns out to be a cheap operation.

**Comment by arzga** [comment]
I proposed a patch in `speech-recognition-polyfill` repo that could be applied without API changes.

https://github.com/speechly/speech-recognition-polyfill/issues/30#issuecomment-1288656895

It seems that modern browsers work OK with this approach, including Chrome: Even though there is a "blinking red dot animation" in the browser interface this seems to be purely cosmetic and recording works from the get-go.

**Comment by arzga** [comment]
Closing due to https://github.com/speechly/speech-recognition-polyfill/issues/30 has been merged.

There is also draft PR [here](https://github.com/speechly/speechly/pull/231) for implementing this also at browser-client level, but it's fate is not decided.
